server:
  port: ${PORT:8080}
  servlet:
    context-path: "/api"

spring:
  application:
    name: inventory-management

  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS}

  jpa:
    hibernate:
      ddl-auto: ${DDL_MODE}
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        dialect: ${DB_DIALECT}

logging:
  level:
    root: INFO
    '[org.springframework.web]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.flywaydb]': DEBUG